apiVersion: v1
baseDomain: butterflycluster.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: ocp4
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.1.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 192.168.1.21
    cluster: cosmo-core
    datacenter: butterflycluster
    defaultDatastore: Roots
    ingressVIP: 192.168.1.22
    network: VM Network
    password: "" # Removed for security
    username: "" # Removed for security
    vCenter: vcenter.butterflycluster.com
    clusterOSImage: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.6/4.6.1/rhcos-vmware.x86_64.ova
publish: External
pullSecret: "" # Removed for security
sshKey: "" # Removed for security