---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${USER_NAME}-edit
  namespace: bomber1
subjects:
- kind: User
  name: ${USER_NAME}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: bomber1
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: example-limits
  namespace: bomber1
spec:
  limits:
  - type: Pod
    max:
      memory: 2Gi
      cpu: "2"
    min:
      memory: 100Mi
      cpu: "0.5"
  - type: Container
    default:
      memory: 500Mi
      cpu: "1"
    defaultRequest:
      memory: 200Mi
      cpu: "0.5"
    max:
      memory: 1Gi
      cpu: "2"
    min:
      memory: 100Mi
      cpu: "0.5"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${USER_NAME}-edit
  namespace: backstage-system
subjects:
- kind: User
  name: ${USER_NAME}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: backstage-system
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: example-limits
  namespace: backstage-system
spec:
  limits:
  - type: Pod
    max:
      memory: 2Gi
      cpu: "2"
    min:
      memory: 100Mi
      cpu: "0.5"
  - type: Container
    default:
      memory: 500Mi
      cpu: "1"
    defaultRequest:
      memory: 200Mi
      cpu: "0.5"
    max:
      memory: 1Gi
      cpu: "2"
    min:
      memory: 100Mi
      cpu: "0.5"
