plugin: community.vmware.vmware_vm_inventory
hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
username: "{{ lookup('env', 'VMWARE_USER') }}"
password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
validate_certs: false

properties:
  - name
  - guest.ipAddress
  - runtime.powerState
  - config.template

filters:
  - runtime.powerState == "poweredOn"
  - config.template == false

hostnames:
  - name

compose:
  ansible_host: guest.ipAddress

groups:
  linux_nodes: true
