apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://192.168.1.189:6443
  name: k3s-cluster
contexts:
- context:
    cluster: k3s-cluster
    namespace: backstage-xyz
    user: new-backstage-sa
  name: backstage-context
current-context: backstage-context
users:
- name: new-backstage-sa
  user:
    tokenFile: ./token-file
