apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csv-viewer
rules:
  - apiGroups: ["operators.coreos.com"]
    resources: ["clusterserviceversions"]
    verbs: ["get", "list", "watch"]
