apiVersion: apps.gitlab.com/v1beta2
kind: Runner
metadata:
  name: gitlab-runner
spec:
  gitlabUrl: https://eros.butterflycluster.com
  buildImage: alpine
  token: gitlab-runner-secret
  tags: openshift