apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openshift-operators
  name: gitlab-runner-viewer
rules:
  - apiGroups: ["apps.gitlab.com"]
    resources: ["runners"]
    verbs: ["get", "list", "watch"]
