# config.yaml
esxi:
  user: "root"
  password: "Password1!"
  hosts:
    - "192.168.1.170"
    - "192.168.1.171"
    - "192.168.1.100"
    - "192.168.1.72"
    - "192.168.1.175"

datastore:
  name: "hermes"
  nas_ip: "192.168.1.182"
  nas_path: "/virtual_machines"

vcenter:
  # ESXi host where the vCenter Appliance VM lives
  esxi_host: "192.168.1.170"

  # The VM name of the vCenter Appliance, as seen in `vim-cmd vmsvc/getallvms`
  appliance_vm_name: "vcenter6.7-marinus"

  # vSphere API endpoint (FQDN or VIP of your vCenter)
  api_host: "192.168.1.200"
  api_user: "administrator@vsphere.local"
  api_password: "Password1!"

  # Other VMs you want to start via the vCenter API
  vms_to_start:
    - "mars"
    - "helios"
    - cygnus
    - elara
