stages:
  - build
  - push

variables:
  IMAGE_NAME: "elara.butterflycluster.com/repository/prod-docke/vault-secret-fetcher"
  IMAGE_VERSION: "1.0.0"
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --no-cache docker

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$IMAGE_VERSION .

push:
  stage: push
  script:
    - echo "Setting up Docker authentication..."
    - mkdir -p ~/.docker
    - echo $DOCKER_AUTH_CONFIG > ~/.docker/config.json
    - echo "Pushing Docker image with latest tag..."
    - docker push $IMAGE_NAME:latest
    - echo "Pushing Docker image with version tag..."
    - docker push $IMAGE_NAME:$IMAGE_VERSION
  only:
    - main

after_script:
  - rm -rf ~/.docker
